<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="renderer" content="webkit">
<meta name="applicable-device" content="pc,mobile">
<title>多米(DuomiCms)-免费影视管理系统-Power by DuomiCms</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/dmcms/duomiui/default/css/style.css" rel="stylesheet">
<script>var sitePath='dmcms/'</script>
<script src="/dmcms/duomiui/default/js/jquery-1.4.4.min.js"></script>
<script src="/dmcms/duomiui/default/js/common.js"></script>
<script src="/dmcms/duomiui/default/js/function.js"></script>
<script src="/dmcms/duomiui/default/js/jquery.lazyload.js"></script>
<link href="/dmcms/favicon.ico" type="image/x-icon" rel="icon">
<link href="/dmcms/favicon.ico" type="image/x-icon" rel="shortcut icon">
<!--[if lt IE 9]>
<script src="/dmcms/duomiui/default/js/html5shiv.min.js"></script>
<script src="/dmcms/duomiui/default/js/respond.min.js"></script>
<![endif]-->
<script src="/dmcms/duomiui/default/js/jquery.superslide.js" type="text/javascript"></script>
</head>
<body>
<div class="header-all">
  <div class="top clearfix">
    <ul class="logo"><a href="/dmcms/"><img src="/dmcms/duomiui/default/images/logo.jpg" title="多米(DuomiCms)"></a></ul>
    <ul class="top-nav">
      <li><a class="now" href="/dmcms/">首页</a></li>
      
      
      <li class="" _t_nav="topnav-1"><a href="/dmcms/list/?1.html">电影<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-2"><a href="/dmcms/list/?2.html">电视剧<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-3"><a href="/dmcms/list/?3.html">综艺<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-4"><a href="/dmcms/list/?4.html">动漫<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      <li><a href="/dmcms/topic/?1.html">专题</a></li>
      <!--li class="" _t_nav="topnav-news"><a href="/dmcms/news/">新闻<i class="sjbgs"></i><i class="sjbgx"></i></a></li-->
      <li><a href="/dmcms/interface/gbook.php">留言</a></li>
    </ul>
    <ul class="search so">
      <form name="formsearch" id="formsearch" action='/search.php' method="post"  target="_self" autocomplete="off">
          <input class="input" name="searchword" type="text" id="keyword" placeholder="请输入影片或演员名" />
          <div class="so-key"><a href='/dmcms/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DA'>关键词A</a> <a href='/dmcms/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DB'>关键词B</a> <a href='/dmcms/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DC'>关键词C</a> <a href='/dmcms/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DD'>关键词D</a> <a href='/dmcms/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DE'>关键词E</a> </div>
          <input class="imgbt" type="submit" value=""/>
      </form>
    </ul>
    <ul class="nav-qt aa">
      <li class="bb"><a href="javascript:void(0)" onMouseOver="$MH.showHistory(1);"><i class="jl"></i>观看历史</a>
      <div class="cc">
	  <script type="text/javascript" src="dmcms//duomiui/default/js/history.js"></script>
          <script type="text/javascript">$MH.limit=10;$MH.WriteHistoryBox(180,170,'font');$MH.recordHistory({name:'{playpage:name}',link:'{playpage:url}',pic:'{playpage:pic}'})</script></div>
      </li>
      <li class="bb"><strong class="ma"><i class="mabg"></i>手机观看</strong>
      <div class="cc maw"><i class="ewmbg"></i><p>扫描二维码用手机观看</p></div>  
      </li>
      <li class="bb member"><strong class="ma"><i class="mbbg"></i></strong>
        <div class="cc mbp">{duomicms:member}</div> 
      </li>
    </ul>
    <ul class="sj-search">
      <li class="sbtn2"><i class="sjbg-search"></i></li>
    </ul>
    <ul class="sj-nav">
      <li class="sbtn1"><i class="sjbg-nav"></i></li>
    </ul>
    <ul class="sj-navhome">
      <li><a href="/dmcms/"><i class="sjbg-home"></i></a></li>
    </ul>  
  </div>
  <div class="nav-down clearfix">
  
  
  <div id="topnav-1" class="nav-down-1" style="display:none;" _t_nav="topnav-1">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/dmcms/list/?5.html">动作片</a></li>
           
      <li><a href="/dmcms/list/?6.html">喜剧片</a></li>
           
      <li><a href="/dmcms/list/?7.html">爱情片</a></li>
           
      <li><a href="/dmcms/list/?8.html">科幻片</a></li>
           
      <li><a href="/dmcms/list/?9.html">剧情片</a></li>
           
      <li><a href="/dmcms/list/?10.html">恐怖片</a></li>
           
      <li><a href="/dmcms/list/?11.html">战争片</a></li>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-2" class="nav-down-1" style="display:none;" _t_nav="topnav-2">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/dmcms/list/?12.html">大陆剧</a></li>
           
      <li><a href="/dmcms/list/?13.html">港台剧</a></li>
           
      <li><a href="/dmcms/list/?14.html">日韩剧</a></li>
           
      <li><a href="/dmcms/list/?15.html">欧美剧</a></li>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-3" class="nav-down-1" style="display:none;" _t_nav="topnav-3">
    <div class="nav-down-2 clearfix">
    <ul>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-4" class="nav-down-1" style="display:none;" _t_nav="topnav-4">
    <div class="nav-down-2 clearfix">
    <ul>
      
    </ul>
    </div>
  </div>
  
  
  <div id="topnav-news" class="nav-down-1" style="display:none;" _t_nav="topnav-news">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/dmcms/articlelist/?16.html">影视资讯</a></li>
           
      <li><a href="/dmcms/articlelist/?17.html">剧情介绍</a></li>
      
    </ul>
    </div>
  </div>
  <div id="sj-nav-1" class="nav-down-1 sy1 sj-noover" style="display:none;" _s_nav="sj-nav-1">
    <div class="nav-down-2 sj-nav-down-2 clearfix">
    <ul> 
      <li><a href="/dmcms/">首页</a></li>
        
      <li><a href="/dmcms/list/?1.html">电影</a></li>
        
      <li><a href="/dmcms/list/?2.html">电视剧</a></li>
        
      <li><a href="/dmcms/list/?3.html">综艺</a></li>
        
      <li><a href="/dmcms/list/?4.html">动漫</a></li>
        
      <li><a href="/dmcms/list/?5.html">动作片</a></li>
        
      <li><a href="/dmcms/list/?6.html">喜剧片</a></li>
        
      <li><a href="/dmcms/list/?7.html">爱情片</a></li>
        
      <li><a href="/dmcms/list/?8.html">科幻片</a></li>
        
      <li><a href="/dmcms/list/?9.html">剧情片</a></li>
        
      <li><a href="/dmcms/list/?10.html">恐怖片</a></li>
        
      <li><a href="/dmcms/list/?11.html">战争片</a></li>
        
      <li><a href="/dmcms/list/?12.html">大陆剧</a></li>
        
      <li><a href="/dmcms/list/?13.html">港台剧</a></li>
        
      <li><a href="/dmcms/list/?14.html">日韩剧</a></li>
        
      <li><a href="/dmcms/list/?15.html">欧美剧</a></li>
    
      <li><a href="/dmcms/topic/?1.html">专题</a></li>
      <li><a href="/dmcms/news/">新闻</a></li>
      <li><a href="/dmcms/interface/gbook.php">留言</a></li>
    </ul>
    </div>
  </div>
  <div id="sj-nav-search" class="nav-down-1 sy2 sj-noover" style="display:none;" _t_nav1="sj-nav-search">
    <div class="nav-down-2 sj-nav-down-search clearfix">
    <form name="formsearch" id="formsearch" action='/dmcms/search.php' method="post"  target="_self" autocomplete="off">
          <input class="input" name="searchword" type="text" id="keyword" placeholder="输入关键词"/>
          <input class="imgbt" type="submit" value="搜索"/>
      </form>
    </div>
  </div>
</div>
</div>
<div class="topone clearfix"></div>
<div class="channel-focus">
  <div class="channel-silder layout">
    <ul class="channel-silder-cnt">
    
    </ul>
    <ul class="channel-silder-nav">
    
    </ul>
  </div>
</div>
<script type="text/javascript">
	jQuery(".channel-silder").slide({ 
		titCell:".channel-silder-nav li",
		mainCell:".channel-silder-cnt",
		delayTime:800,
		triggerTime:0,
		interTime:5000,
		pnLoop:false,
		autoPage:false,
		autoPlay:true
	});
</script>
<div class="main">
	<div class="index-area clearfix">
    <h1 class="title index-color">推荐影片</h1>
    <ul>
    
    </ul>
    </div>

	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/dmcms/list/?5.html" class="on">动作片</a>
      
      <a href="/dmcms/list/?6.html" class="on">喜剧片</a>
      
      <a href="/dmcms/list/?7.html" class="on">爱情片</a>
      
      <a href="/dmcms/list/?8.html" class="on">科幻片</a>
      
      <a href="/dmcms/list/?9.html" class="on">剧情片</a>
      
      <a href="/dmcms/list/?10.html" class="on">恐怖片</a>
      
      <a href="/dmcms/list/?11.html" class="on">战争片</a>
      
      <a href="/dmcms/list/?1.html">更多»</a>
      </span>
      电影</h1>
    <ul>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/dmcms/list/?12.html" class="on">大陆剧</a>
      
      <a href="/dmcms/list/?13.html" class="on">港台剧</a>
      
      <a href="/dmcms/list/?14.html" class="on">日韩剧</a>
      
      <a href="/dmcms/list/?15.html" class="on">欧美剧</a>
      
      <a href="/dmcms/list/?2.html">更多»</a>
      </span>
      电视剧</h1>
    <ul>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/dmcms/list/?3.html">更多»</a>
      </span>
      综艺</h1>
    <ul>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/dmcms/list/?4.html">更多»</a>
      </span>
      动漫</h1>
    <ul>
    
    </ul>
    </div>
    
</div>
<div class="ylink clearfix">
    
      <a href="http://www.samfea.com" target="_blank">萨夫软件</a>
    
      <a href="http://www.duomicms.net" target="_blank">DuomiCms影视系统</a>
    
</div>
<div class="footer clearfix">
Copyright &#169; 2015-2016 多米(DuomiCms V1.30)影视管理系统 版权所有 备案号   
<p><a href="http://www.duomicms.net/" target="_blank" class="footer-bg"><span class="bg"></span></a></p>
</div>
<div class="gotop"><a class="gotopbg" href="javascript:;" title="返回顶部"></a></div>
</body>
</html>
